mutation ($assignedToFlowcell: Boolean!, $libraryName: String!) {
  updateLibrariesList(assignedToFlowcell: $assignedToFlowcell, libraryName: $libraryName) @client {
    assignedToFlowcell
    libraryName
  }
}
