mutation ($barcode: String!, $wells: [WellWithSamplesInput!]!) {
  createPlateWithSamples(input: { arguments: { barcode: $barcode, wells: $wells } }) {
    plate {
      id
      barcode
      wells {
        plateId
      }
    }
    errors
  }
}
