mutation($flowcells: [FlowcellInput!]!) {
  createOntRun(input: { flowcells: $flowcells }) {
    run {
      id
      flowcells {
        position
        library {
          name
        }
      }
    }
    errors
  }
}
