query ($unassignedToFlowcells: Boolean, $pageNum: Int, $pageSize: Int) {
  libraries: ontLibraries(unassignedToFlowcells: $unassignedToFlowcells, pageNum: $pageNum, pageSize: $pageSize) {
    nodes {
      id
      name
      pool
      poolSize
      tubeBarcode
      plateBarcode
      createdAt
    }
    pageInfo {
      pageCount
      entitiesCount
    }
  }
}