query ($unassignedToFlowcells: Boolean) {
  libraries: ontLibraries(unassignedToFlowcells: $unassignedToFlowcells) {
    id
    name
    pool
    poolSize
    tubeBarcode
    plateBarcode
    createdAt
  }
}