query ($pageNum: Int, $pageSize: Int) {
  runs: ontRuns(pageNum: $pageNum, pageSize: $pageSize) {
    nodes {
      id
      experimentName
      createdAt
      updatedAt
      flowcells {
        library {
          name
        }
      }
    }
    pageInfo {
      pageCount
      entitiesCount
    }
  } 
}
