query ($pageNum: Int, $pageSize: Int) {
  plates: plates(pageNum: $pageNum, pageSize: $pageSize) {
    nodes {
      id
      barcode
      createdAt
    }
    pageInfo {
      pageCount
      entitiesCount
    }
  }
}