mutation poolSamples($plate_barcode: String!) {
  createOntLibraries(
    input: {
      arguments: {
        plateBarcode: $plate_barcode
      }
    }
  )
  {
    tubes {
      barcode
    }
    errors
  }
}