mutation poolSamples($plate_barcode: String!, $tag_set_name: String!, $grouping_direction: String! ) {
  createOntLibraries(
    input: {
      arguments: {
        plateBarcode: $plate_barcode
        tagSetName: $tag_set_name
        wellPrimaryGroupingDirection: $grouping_direction
      }
    }
  )
  {
    tubes { barcode materials { ... on Library { name pool wellRange poolSize } } }
    errors
  }
}