mutation ($plate_barcode: String!) {
  createOntLibraries(input: { arguments: { plateBarcode: $plate_barcode } }) {
    tubes {
      barcode
      materials {
        ... on Library {
          name
        }
      }
    }
    errors
  }
}
