name: Add dependencies to test project board on push

on:
 push:
    branches:
      - y24-060-sanger-access-token
jobs:
 add-to-project-using-github-app:
    name: Add pull request to project using github app
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ vars.PSD_DEMO_APP_ID }}
          application_private_key: ${{ secrets.PSD_DEMO_APP_KEY }}

      - name: Use Application Token to add to project
        uses: actions/add-to-project@v0.5.0
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        with:
          project-url: https://github.com/orgs/sanger/projects/13
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT_ORG_WIDE }}