name: Add dependencies to technical debt project

on:
  pull_request:
    types:
      - labeled

jobs:
  call-add-to-project:
    uses: sanger/.github/.github/workflows/test.yml@master
    secrets:
      app_id: ${{ secrets.ADD_TO_PROJECT_APP_ID_PSD }}
      app_key: ${{ secrets.ADD_TO_PROJECT_APP_KEY_PSD }}
    
  