# Checks that the .release-version file has been updated
name: Check release version

on:
  push:
    branches:
      - dpl-338

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v23
        with:
          files: |
            .release-version
          
      - name: Run step looking for change in the release version
        if: !github.event.pull_request.draft
        run: >-
          if [ "${{ steps.changed-files-specific.outputs.any_changed }}" ==  'false' ]; then
            echo "Please change the release version number"
            exit 1;
          fi
          