name: CI Format

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
jobs:
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master
     
      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Install npm dependencies
        uses: sanger/.github/.github/actions/install/npm@master

      - name: Type check
        run: >-
          npm run type-check

  prettier:
    name: Check format with prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master
     
      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Install npm dependencies
        uses: sanger/.github/.github/actions/install/npm@master

      - name: Run npm pretty
        run: >-
          npm run pretty

  eslint:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master
     
      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Install npm dependencies
        uses: sanger/.github/.github/actions/install/npm@master

      - name: Lint using ESLint
        run: >-
          npm run lint
