name: Deploy JSDoc to GitHub Pages

on:
  push:
    branches:
      - 'master'
      - 'develop'
  workflow_dispatch:

permissions:
  pages: write      # Allow writing to the GitHub Pages
  id-token: write   # Allow OIDC token to be issued

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@y25-098-updates-on-actions-1

      - name: Install npm dependencies
        uses: sanger/.github/.github/actions/install/npm@y25-098-updates-on-actions-1

      - name: Run jsdoc and organize docs
        run: |
          npm run jsdoc
          mkdir -p docs/public
          cp -r public docs/public
          cp public/favicon.ico docs/
          cp -r style_guide.md docs/style_guide.md
            
      - name: Install Python dependencies
        uses: sanger/.github/.github/actions/install/python/dev@y25-098-updates-on-actions-1

      - name: Generate docs
        run: |
          ./generate-docs.sh

      - name: Upload artifact to GitHub Pages
        uses: sanger/.github/.github/actions/docs/upload@master
        with:
          path: docs

  deploy:
    runs-on: ubuntu-latest
    needs: build  # The deploy job will only run if the build job is successful

    steps:
      - name: Deploy to GitHub Pages
        uses: sanger/.github/.github/actions/docs/deploy@master
