name: Deploy JSDoc to GitHub Pages

on:
  push:
    branches:
      - 'master'
      - 'develop'
  workflow_dispatch:

permissions:
  pages: write      # Allow writing to the GitHub Pages
  id-token: write   # Allow OIDC token to be issued

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master
      
      - name: Install dependencies with npm
        uses: sanger/.github/.github/actions/install/npm@master
            
      - name: Run jsdoc and organize docs
        uses: sanger/.github/.github/actions/docs/run/jsdoc@master
            
      - name: Install Python dependencies
        uses: sanger/.github/.github/actions/install/python@master

      - name: Generate docs
        run: |
          ./generate-docs.sh

      - name: Upload artifact to GitHub Pages
        uses: sanger/.github/.github/actions/docs/upload@master
        with:
          path: docs

  deploy:
    runs-on: ubuntu-latest
    needs: build  # The deploy job will only run if the build job is successful

    steps:
      - name: Deploy to GitHub Pages
        uses: sanger/.github/.github/actions/docs/deploy@master
