name: Deploy JSDoc to GitHub Pages

on:
  push:
    branches:
      - 'master'
      - 'develop'
  workflow_dispatch:

permissions:
  pages: write      # Allow writing to the GitHub Pages
  id-token: write   # Allow OIDC token to be issued

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version-file: '.nvmrc'
            cache: 'npm'
      - name: Install dependencides
        run: >-
            npm ci --legacy-peer-deps
      - name: Run jsdoc
        run: |
            npm run jsdoc
            mkdir -p doc/public
            cp -r public doc/public
            cp public/favicon.ico doc/
            cp -r style_guide.md doc/style_guide.md
     
      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: doc  # Path to the folder containing the JS documentation (default is 'docs')

  deploy:
    runs-on: ubuntu-latest
    needs: build  # The deploy job will only run if the build job is successful

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
